#!/bin/bash

# path the CSS phoebus executable
PHOEBUS="/APSshare/bin/phoebus"

# path to urRobot support module
URROBOT_PATH="/net/s100dserv/xorApps/epics/synApps_6_3/support/urRobot"

# ioc prefixes
P="urExample:"
R=""

#######################################

export EPICS_APP=$(cd "$(dirname "$BASH_SOURCE")"; cd -P "$(dirname "$(readlink "$BASH_SOURCE" || echo .)")"; pwd)
export EPICS_APP_UI_DIR=${URROBOT_PATH}/urRobotApp/op/bob
export UI_FILE1=${1:-${DEFAULT_UI_FILE:-urRobot.bob}}
export UI_FILE_MACROS=${2:-"P=${P}"}

#######################################
# start CSS-phoebus
${PHOEBUS} -layout $EPICS_APP/phoebus.layout -resource "file:${EPICS_APP_UI_DIR}/${UI_FILE1}?${UI_FILE_MACROS}&target=window"
